### ISSUE TITLE
Model Checkpoint

### ISSUE THREAD

**Issue by jiahuiLeee** [YuweiYin/FinPT#1]
Limited by computer resources, could you please provide the trained model parameters file? Thanks a lot!!!

**Comment by YuweiYin** [comment]
> Limited by computer resources, could you please provide the trained model parameters file? Thanks a lot!!!

Thanks for your attention.

We did not upload the checkpoints (now that I'm not affiliated with HKU...) since the framework/pipeline is easy to implement, and the fine-tuning of LLMs is to use [Trainer](https://huggingface.co/docs/transformers/main_classes/trainer) to perform [Causal language modeling](https://huggingface.co/docs/transformers/en/tasks/language_modeling). Fine-tuning on GPT-2 should not cost that much. Though slower, an affordable GPU or even a CPU is feasible.
